# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='pic_folder/B.png', upload_to='pics/'),
        ),
    ]
