# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_image',
        ),
    ]
