# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='pics/B.png', upload_to='pics/'),
        ),
    ]
